# Generated by Django 6.0.4 on 2026-05-05 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('variety', models.CharField(choices=[('Koroneiki', 'Koroneiki'), ('Arbequina', 'Arbequina'), ('Picual', 'Picual'), ('Frantoio', 'Frantoio')], max_length=50)),
                ('tree_count', models.IntegerField()),
                ('area_hectares', models.FloatField()),
                ('planting_year', models.IntegerField()),
                ('irrigation_type', models.CharField(default='Drip', max_length=50)),
                ('soil_type', models.CharField(default='Loam', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Dormant', 'Dormant'), ('New', 'New Planting')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity', models.FloatField(help_text='Quantity in kilograms')),
                ('quality_grade', models.CharField(default='Standard', max_length=50)),
                ('oil_yield', models.FloatField(blank=True, help_text='Oil yield in percentage', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='core.grove')),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('Pruning', 'Pruning'), ('Irrigation', 'Irrigation'), ('Fertilization', 'Fertilization'), ('Pest Control', 'Pest Control'), ('Disease Treatment', 'Disease Treatment'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='core.grove')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
